/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low":      "#f3f4f6",
        "on-primary":                 "#ffffff",
        "on-primary-fixed":           "#001b3f",
        "surface-container":          "#edeef0",
        "on-primary-container":       "#89a5dd",
        "primary-fixed":              "#d7e2ff",
        "on-tertiary-container":      "#4f3d00",
        "on-tertiary":                "#ffffff",
        "on-background":              "#191c1e",
        "surface-tint":               "#415e91",
        "on-primary-fixed-variant":   "#284678",
        "on-tertiary-fixed-variant":  "#584400",
        "tertiary-fixed":             "#ffe08e",
        "on-surface-variant":         "#43474f",
        "tertiary-container":         "#cea62b",
        "on-secondary":               "#ffffff",
        "tertiary":                   "#755b00",
        "on-tertiary-fixed":          "#241a00",
        "inverse-on-surface":         "#f0f1f3",
        "secondary-container":        "#7fbafd",
        "surface-variant":            "#e1e2e4",
        "tertiary-fixed-dim":         "#ecc246",
        "on-error-container":         "#93000a",
        "inverse-surface":            "#2e3132",
        "on-secondary-fixed":         "#001d36",
        "on-secondary-container":     "#00497e",
        "secondary-fixed":            "#d1e4ff",
        "on-secondary-fixed-variant": "#00497d",
        "surface":                    "#f8f9fb",
        "surface-container-high":     "#e7e8ea",
        "error":                      "#ba1a1a",
        "outline-variant":            "#c4c6d0",
        "error-container":            "#ffdad6",
        "primary-fixed-dim":          "#abc7ff",
        "primary-container":          "#1a3a6b",
        "outline":                    "#747780",
        "on-surface":                 "#191c1e",
        "secondary":                  "#18619e",
        "on-error":                   "#ffffff",
        "surface-dim":                "#d9dadc",
        "background":                 "#f8f9fb",
        "surface-bright":             "#f8f9fb",
        "inverse-primary":            "#abc7ff",
        "surface-container-highest":  "#e1e2e4",
        "secondary-fixed-dim":        "#9ecaff",
        "primary":                    "#002451",
        "surface-container-lowest":   "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
